# Generated by Django 4.1 on 2022-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchespredictions',
            name='userprediction',
            field=models.CharField(choices=[('A', 'Teama'), ('B', 'Teamb'), ('draw', 'Draw'), ('non', 'No Prediction')], default='non', max_length=30),
        ),
    ]
