# Generated by Django 4.1 on 2022-09-18 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0003_alter_fixture_result_remove_matchespredictions_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchespredictions',
            name='user',
        ),
        migrations.AddField(
            model_name='matchespredictions',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
