# Generated by Django 4.1 on 2022-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_matchespredictions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='fulltime',
            field=models.BooleanField(default=False),
        ),
    ]
