# Generated by Django 4.1 on 2022-09-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_fixture_fulltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='teamA',
            new_name='Away',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='teamB',
            new_name='Home',
        ),
        migrations.RemoveField(
            model_name='matchpoint',
            name='user',
        ),
        migrations.AlterField(
            model_name='matchespredictions',
            name='userprediction',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Away'), ('draw', 'Draw'), ('non', 'No Prediction')], default='non', max_length=30),
        ),
        migrations.AlterField(
            model_name='matchpoint',
            name='Fixture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league.matchespredictions'),
        ),
    ]
