# Generated by Django 4.1 on 2022-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_rename_teama_fixture_away_rename_teamb_fixture_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='Score',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='matchespredictions',
            name='userprediction',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('draw', 'Draw'), ('non', 'No Prediction')], default='non', max_length=30),
        ),
    ]
