# Generated by Django 4.1 on 2022-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_fixture_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='awayimg',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fixture',
            name='homeimg',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fixture',
            name='matchtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
