# Generated by Django 4.0.6 on 2022-11-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_fixture_awayimg_alter_fixture_homeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='matchid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
