# Generated by Django 4.0.6 on 2022-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_fixture_matchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='Score',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
