# Generated by Django 4.0.6 on 2022-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_fixture_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchespredictions',
            name='has_predicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchespredictions',
            name='userprediction',
            field=models.CharField(choices=[('Home', 'Home'), ('Away', 'Away'), ('draw', 'Draw'), ('non', 'No Prediction'), ('out', 'Stay Out')], default='non', max_length=30),
        ),
    ]
