# Generated by Django 4.1 on 2022-09-06 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('point', models.IntegerField()),
                ('team', models.CharField(choices=[('Neutral', 'Neutral'), ('Arsenal', 'Arsenal'), ('Aston Villa FC', 'Aston Villa Fc'), (' Bournemouth AFC', 'Bournemouth Afc'), ('Brentford', 'Brentford'), ('Brighton & Hove Albion', 'Brighton And Hove Albion'), ('Chelsea', 'Chelsea'), ('Crystal Palace', 'Crystal Palace'), ('Everton FC', 'Everton Fc'), ('Fulham', 'Fulham'), ('Leicester City FC ', 'Leicester City Fc'), ('Leeds United', 'Leeds United'), ('Liverpool FC', 'Liverpool Fc'), ('Manchester City FC', 'Manchester City Fc'), ('Manchester United FC', 'Manchester United Fc'), ('Newcastle United', 'Newcastle United'), ('Nottingham Forest', 'Nottingham Forest'), ('Southampton FC', 'Southampton Fc'), ('Tottenham Hotspur FC', 'Tottenham Hotspur Fc'), ('West Ham United', 'West Ham United'), ('Wolverhampton Wanderers', 'Wolverhampton Wanderers')], default='Neutral', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
