# Generated by Django 4.1 on 2022-09-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='point',
            field=models.IntegerField(),
        ),
    ]
