# Generated by Django 4.0.6 on 2022-11-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_addduser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addduser_number',
            name='alreadyuser',
            field=models.BooleanField(default=False),
        ),
    ]
