# Generated by Django 4.0.6 on 2022-11-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_addduser_number_alreadyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='team',
            field=models.CharField(choices=[('Uruguay', 'Uruguay'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Argentina', 'Argentina'), ('Ghana', 'Ghana'), ('Brazil', 'Brazil'), ('Portugal', 'Portugal'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('England', 'England'), ('United States', 'United States'), ('Korea Republic', 'Korea Republic'), ('France', 'France'), ('Australia', 'Australia'), ('Serbia', 'Serbia'), ('Cameroon', 'Cameroon'), ('Denmark', 'Denmark'), ('Switzerland', 'Switzerland'), ('Ecuador', 'Ecuador'), ('Costa_Rica', 'Costa Rica'), ('Poland', 'Poland'), ('Croatia', 'Croatia'), ('Saudi Arabia', 'Saudi Arabia'), ('Tunisia', 'Tunisia'), ('Senegal', 'Senegal'), ('Belgium', 'Belgium'), ('Morocco', 'Morocco'), ('Canada', 'Canada'), ('Wales', 'Wales'), ('Iran', 'Iran'), ('Qatar', 'Qatar'), ('Netherlands', 'Netherlands')], default='Japan', max_length=30),
        ),
    ]
